// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Uchu.Core.Providers;

#nullable disable

namespace Uchu.Core.Migrations
{
    [DbContext(typeof(PostgresContext))]
    [Migration("20220203130407_RacingLeaderboards")]
    partial class RacingLeaderboards
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Uchu.Core.ActivityScore", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Activity")
                        .HasColumnType("integer");

                    b.Property<int>("BestLapTime")
                        .HasColumnType("integer");

                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint");

                    b.Property<long>("LastPlayed")
                        .HasColumnType("bigint");

                    b.Property<int>("NumPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("Time")
                        .HasColumnType("integer");

                    b.Property<int>("Week")
                        .HasColumnType("integer");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.Property<int>("Zone")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ActivityScores");
                });

            modelBuilder.Entity("Uchu.Core.Character", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("BaseHealth")
                        .HasColumnType("integer");

                    b.Property<int>("BaseImagination")
                        .HasColumnType("integer");

                    b.Property<long>("Currency")
                        .HasColumnType("bigint");

                    b.Property<int>("CurrentArmor")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentHealth")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentImagination")
                        .HasColumnType("integer");

                    b.Property<string>("CustomName")
                        .IsRequired()
                        .HasMaxLength(33)
                        .HasColumnType("character varying(33)");

                    b.Property<long>("EyeStyle")
                        .HasColumnType("bigint");

                    b.Property<long>("EyebrowStyle")
                        .HasColumnType("bigint");

                    b.Property<bool>("FreeToPlay")
                        .HasColumnType("boolean");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("HairColor")
                        .HasColumnType("bigint");

                    b.Property<long>("HairStyle")
                        .HasColumnType("bigint");

                    b.Property<int>("InventorySize")
                        .HasColumnType("integer");

                    b.Property<bool>("LandingByRocket")
                        .HasColumnType("boolean");

                    b.Property<long>("LastActivity")
                        .HasColumnType("bigint");

                    b.Property<long>("LastClone")
                        .HasColumnType("bigint");

                    b.Property<int>("LastInstance")
                        .HasColumnType("integer");

                    b.Property<int>("LastZone")
                        .HasColumnType("integer");

                    b.Property<int>("LaunchedRocketFrom")
                        .HasColumnType("integer");

                    b.Property<long>("Level")
                        .HasColumnType("bigint");

                    b.Property<long>("Lh")
                        .HasColumnType("bigint");

                    b.Property<int>("MaximumArmor")
                        .HasColumnType("integer");

                    b.Property<int>("MaximumHealth")
                        .HasColumnType("integer");

                    b.Property<int>("MaximumImagination")
                        .HasColumnType("integer");

                    b.Property<long>("MouthStyle")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(33)
                        .HasColumnType("character varying(33)");

                    b.Property<bool>("NameRejected")
                        .HasColumnType("boolean");

                    b.Property<long>("PantsColor")
                        .HasColumnType("bigint");

                    b.Property<long>("Rh")
                        .HasColumnType("bigint");

                    b.Property<string>("Rocket")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<long>("ShirtColor")
                        .HasColumnType("bigint");

                    b.Property<long>("ShirtStyle")
                        .HasColumnType("bigint");

                    b.Property<string>("SpawnLocationName")
                        .HasMaxLength(33)
                        .HasColumnType("character varying(33)");

                    b.Property<float?>("SpawnPositionX")
                        .HasColumnType("real");

                    b.Property<float?>("SpawnPositionY")
                        .HasColumnType("real");

                    b.Property<float?>("SpawnPositionZ")
                        .HasColumnType("real");

                    b.Property<float?>("SpawnRotationW")
                        .HasColumnType("real");

                    b.Property<float?>("SpawnRotationX")
                        .HasColumnType("real");

                    b.Property<float?>("SpawnRotationY")
                        .HasColumnType("real");

                    b.Property<float?>("SpawnRotationZ")
                        .HasColumnType("real");

                    b.Property<long>("TotalArmorPowerUpsCollected")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalArmorRepaired")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalBricksCollected")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalCurrencyCollected")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalDamageHealed")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalDamageTaken")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalDistanceDriven")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalDistanceTraveled")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalEnemiesSmashed")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalFirstPlaceFinishes")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalImaginationPowerUpsCollected")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalImaginationRestored")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalImaginationUsed")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalLifePowerUpsCollected")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalMissionsCompleted")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalPetsTamed")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalQuickBuildsCompleted")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalRacecarBoostsActivated")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalRacecarWrecks")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalRacesFinished")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalRacingImaginationCratesSmashed")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalRacingImaginationPowerUpsCollected")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalRacingSmashablesSmashed")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalRocketsUsed")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalSmashablesSmashed")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalSuicides")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalTimeAirborne")
                        .HasColumnType("bigint");

                    b.Property<long>("UniverseScore")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("VaultInventorySize")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Uchu.Core.CharacterFlag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint");

                    b.Property<int>("Flag")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Flags");
                });

            modelBuilder.Entity("Uchu.Core.CharacterMail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AttachmentCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("AttachmentCurrency")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("AttachmentLot")
                        .HasColumnType("integer");

                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Read")
                        .HasColumnType("boolean");

                    b.Property<long>("RecipientId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Mails");
                });

            modelBuilder.Entity("Uchu.Core.CharacterTrade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CurrencyA")
                        .HasColumnType("bigint");

                    b.Property<long>("CurrencyB")
                        .HasColumnType("bigint");

                    b.Property<long>("PartyA")
                        .HasColumnType("bigint");

                    b.Property<long>("PartyB")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("Uchu.Core.ChatTranscript", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("Author")
                        .HasColumnType("bigint");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<long>("Receiver")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ChatTranscript");
                });

            modelBuilder.Entity("Uchu.Core.Friend", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("BestFriend")
                        .HasColumnType("boolean");

                    b.Property<long>("FriendA")
                        .HasColumnType("bigint");

                    b.Property<long>("FriendB")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Friends");
                });

            modelBuilder.Entity("Uchu.Core.FriendRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("BestFriend")
                        .HasColumnType("boolean");

                    b.Property<long>("Receiver")
                        .HasColumnType("bigint");

                    b.Property<long>("Sender")
                        .HasColumnType("bigint");

                    b.Property<bool>("Sent")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("FriendRequests");
                });

            modelBuilder.Entity("Uchu.Core.Guild", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("Uchu.Core.GuildInvite", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("RecipientId")
                        .HasColumnType("bigint");

                    b.Property<long>("SenderId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("GuildInvites");
                });

            modelBuilder.Entity("Uchu.Core.InventoryItem", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint");

                    b.Property<long>("Count")
                        .HasColumnType("bigint");

                    b.Property<string>("ExtraInfo")
                        .HasColumnType("text");

                    b.Property<int>("InventoryType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsBound")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("boolean");

                    b.Property<int>("Lot")
                        .HasColumnType("integer");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<int>("Slot")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("Uchu.Core.Mission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint");

                    b.Property<int>("CompletionCount")
                        .HasColumnType("integer");

                    b.Property<long>("LastCompletion")
                        .HasColumnType("bigint");

                    b.Property<int>("MissionId")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Missions");
                });

            modelBuilder.Entity("Uchu.Core.MissionTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MissionId")
                        .HasColumnType("integer");

                    b.Property<int>("TaskId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MissionId");

                    b.ToTable("MissionTasks");
                });

            modelBuilder.Entity("Uchu.Core.MissionTaskValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<int>("MissionTaskId")
                        .HasColumnType("integer");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("MissionTaskId");

                    b.ToTable("MissionTaskValue");
                });

            modelBuilder.Entity("Uchu.Core.SessionCache", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint");

                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("ZoneId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SessionCaches");
                });

            modelBuilder.Entity("Uchu.Core.TradeTransactionItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<long>("Party")
                        .HasColumnType("bigint");

                    b.Property<long>("TradeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TradeId");

                    b.ToTable("TransactionItems");
                });

            modelBuilder.Entity("Uchu.Core.UnlockedEmote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint");

                    b.Property<int>("EmoteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("UnlockedEmote");
                });

            modelBuilder.Entity("Uchu.Core.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Banned")
                        .HasColumnType("boolean");

                    b.Property<string>("BannedReason")
                        .HasColumnType("text");

                    b.Property<int>("CharacterIndex")
                        .HasColumnType("integer");

                    b.Property<string>("CustomLockout")
                        .HasColumnType("text");

                    b.Property<bool>("FirstTimeOnSubscription")
                        .HasColumnType("boolean");

                    b.Property<bool>("FreeToPlay")
                        .HasColumnType("boolean");

                    b.Property<int>("GameMasterLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<bool>("Sso")
                        .HasColumnType("boolean");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(33)
                        .HasColumnType("character varying(33)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Uchu.Core.Character", b =>
                {
                    b.HasOne("Uchu.Core.User", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Uchu.Core.CharacterFlag", b =>
                {
                    b.HasOne("Uchu.Core.Character", "Character")
                        .WithMany("Flags")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Uchu.Core.GuildInvite", b =>
                {
                    b.HasOne("Uchu.Core.Guild", "Guild")
                        .WithMany("Invites")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Uchu.Core.InventoryItem", b =>
                {
                    b.HasOne("Uchu.Core.Character", "Character")
                        .WithMany("Items")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Uchu.Core.Mission", b =>
                {
                    b.HasOne("Uchu.Core.Character", "Character")
                        .WithMany("Missions")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Uchu.Core.MissionTask", b =>
                {
                    b.HasOne("Uchu.Core.Mission", "Mission")
                        .WithMany("Tasks")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("Uchu.Core.MissionTaskValue", b =>
                {
                    b.HasOne("Uchu.Core.MissionTask", "MissionTask")
                        .WithMany("Values")
                        .HasForeignKey("MissionTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MissionTask");
                });

            modelBuilder.Entity("Uchu.Core.TradeTransactionItem", b =>
                {
                    b.HasOne("Uchu.Core.CharacterTrade", "Trade")
                        .WithMany("TransactionItems")
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trade");
                });

            modelBuilder.Entity("Uchu.Core.UnlockedEmote", b =>
                {
                    b.HasOne("Uchu.Core.Character", "Character")
                        .WithMany("UnlockedEmotes")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Uchu.Core.Character", b =>
                {
                    b.Navigation("Flags");

                    b.Navigation("Items");

                    b.Navigation("Missions");

                    b.Navigation("UnlockedEmotes");
                });

            modelBuilder.Entity("Uchu.Core.CharacterTrade", b =>
                {
                    b.Navigation("TransactionItems");
                });

            modelBuilder.Entity("Uchu.Core.Guild", b =>
                {
                    b.Navigation("Invites");
                });

            modelBuilder.Entity("Uchu.Core.Mission", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Uchu.Core.MissionTask", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("Uchu.Core.User", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
