//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uchu.Core.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Uchu.Core.Resources.ResourceStrings", typeof(ResourceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string BitReader_Read_NullReaderException {
            get {
                return ResourceManager.GetString("BitReader_Read_NullReaderException", resourceCulture);
            }
        }
        
        internal static string BitReader_Read_NullSerializableException {
            get {
                return ResourceManager.GetString("BitReader_Read_NullSerializableException", resourceCulture);
            }
        }
        
        internal static string BitReader_Readbytes_NullReaderException {
            get {
                return ResourceManager.GetString("BitReader_Readbytes_NullReaderException", resourceCulture);
            }
        }
        
        internal static string BitReader_ReadString_NullReaderException {
            get {
                return ResourceManager.GetString("BitReader_ReadString_NullReaderException", resourceCulture);
            }
        }
        
        internal static string BitWriter_Write_NullWriterException {
            get {
                return ResourceManager.GetString("BitWriter_Write_NullWriterException", resourceCulture);
            }
        }
        
        internal static string BitWriter_WriteString_NullWriterException {
            get {
                return ResourceManager.GetString("BitWriter_WriteString_NullWriterException", resourceCulture);
            }
        }
        
        internal static string DatabaseCache_SetCharacter_NullEndpointException {
            get {
                return ResourceManager.GetString("DatabaseCache_SetCharacter_NullEndpointException", resourceCulture);
            }
        }
        
        internal static string DatabaseCache_SetZone_NullEndpointException {
            get {
                return ResourceManager.GetString("DatabaseCache_SetZone_NullEndpointException", resourceCulture);
            }
        }
        
        internal static string DatabaseCache_GetSessionAsync_NullEndpointException {
            get {
                return ResourceManager.GetString("DatabaseCache_GetSessionAsync_NullEndpointException", resourceCulture);
            }
        }
        
        internal static string DatabaseCache_RegisterKey_NullEndpointException {
            get {
                return ResourceManager.GetString("DatabaseCache_RegisterKey_NullEndpointException", resourceCulture);
            }
        }
        
        internal static string DatabaseCache_DeleteSession_NullEndpointException {
            get {
                return ResourceManager.GetString("DatabaseCache_DeleteSession_NullEndpointException", resourceCulture);
            }
        }
        
        internal static string RakConnectionExtensions_Send_ConnectionNullException {
            get {
                return ResourceManager.GetString("RakConnectionExtensions_Send_ConnectionNullException", resourceCulture);
            }
        }
        
        internal static string RakConnectionExtensions_Send_StreamNullException {
            get {
                return ResourceManager.GetString("RakConnectionExtensions_Send_StreamNullException", resourceCulture);
            }
        }
        
        internal static string GeneralHandler_Handshake_PacketNullException {
            get {
                return ResourceManager.GetString("GeneralHandler_Handshake_PacketNullException", resourceCulture);
            }
        }
        
        internal static string HandshakePacket_Deserialize_ReaderNullException {
            get {
                return ResourceManager.GetString("HandshakePacket_Deserialize_ReaderNullException", resourceCulture);
            }
        }
        
        internal static string HandshakePacket_Serialize_WriterNullException {
            get {
                return ResourceManager.GetString("HandshakePacket_Serialize_WriterNullException", resourceCulture);
            }
        }
        
        internal static string RedisSessionCache_ConfigNullException {
            get {
                return ResourceManager.GetString("RedisSessionCache_ConfigNullException", resourceCulture);
            }
        }
        
        internal static string RedisSessionCache_SetCharacter_EndpointNullException {
            get {
                return ResourceManager.GetString("RedisSessionCache_SetCharacter_EndpointNullException", resourceCulture);
            }
        }
        
        internal static string RedisSessionCache_SetZone_EndpointNullException {
            get {
                return ResourceManager.GetString("RedisSessionCache_SetZone_EndpointNullException", resourceCulture);
            }
        }
        
        internal static string RedisSessioncache_GetSessionAsync_EndpointNullException {
            get {
                return ResourceManager.GetString("RedisSessioncache_GetSessionAsync_EndpointNullException", resourceCulture);
            }
        }
        
        internal static string RedisSessionCache_RegisterKey_EndpointNullException {
            get {
                return ResourceManager.GetString("RedisSessionCache_RegisterKey_EndpointNullException", resourceCulture);
            }
        }
        
        internal static string RedisSessionCache_DeleteSession_EndpointNullException {
            get {
                return ResourceManager.GetString("RedisSessionCache_DeleteSession_EndpointNullException", resourceCulture);
            }
        }
        
        internal static string DisconnectNotifyPacket_Serialize_PacketWriterNullException {
            get {
                return ResourceManager.GetString("DisconnectNotifyPacket_Serialize_PacketWriterNullException", resourceCulture);
            }
        }
        
        internal static string DisconnectNotifyPacket_Deserialize_ReaderNullException {
            get {
                return ResourceManager.GetString("DisconnectNotifyPacket_Deserialize_ReaderNullException", resourceCulture);
            }
        }
        
        internal static string StandardCommandHandler_AddUser_ArgumentsNullException {
            get {
                return ResourceManager.GetString("StandardCommandHandler_AddUser_ArgumentsNullException", resourceCulture);
            }
        }
        
        internal static string StandardCommandHandler_RemoveUser_ArgumentsNullException {
            get {
                return ResourceManager.GetString("StandardCommandHandler_RemoveUser_ArgumentsNullException", resourceCulture);
            }
        }
        
        internal static string StandardCommandHandler_RemoveUser_ConfirmationMessage {
            get {
                return ResourceManager.GetString("StandardCommandHandler_RemoveUser_ConfirmationMessage", resourceCulture);
            }
        }
        
        internal static string StandardCommandHandler_BanUser_ArgumentsNullException {
            get {
                return ResourceManager.GetString("StandardCommandHandler_BanUser_ArgumentsNullException", resourceCulture);
            }
        }
        
        internal static string StandardCommandHandler_PardonUser_ArgumentsNullException {
            get {
                return ResourceManager.GetString("StandardCommandHandler_PardonUser_ArgumentsNullException", resourceCulture);
            }
        }
        
        internal static string StandardCommandHandler_ApproveUsername_ArgumentsNullException {
            get {
                return ResourceManager.GetString("StandardCommandHandler_ApproveUsername_ArgumentsNullException", resourceCulture);
            }
        }
        
        internal static string StandardCommandHandler_RejectUserNames_ArgumentsNullException {
            get {
                return ResourceManager.GetString("StandardCommandHandler_RejectUserNames_ArgumentsNullException", resourceCulture);
            }
        }
        
        internal static string StandardCommandHandler_SetGameMasterLevel_ArgumentsNullException {
            get {
                return ResourceManager.GetString("StandardCommandHandler_SetGameMasterLevel_ArgumentsNullException", resourceCulture);
            }
        }
        
        internal static string LocalResources_GetStream_PathNullException {
            get {
                return ResourceManager.GetString("LocalResources_GetStream_PathNullException", resourceCulture);
            }
        }
        
        internal static string ClientHandler_ValidateClient_PacketNullException {
            get {
                return ResourceManager.GetString("ClientHandler_ValidateClient_PacketNullException", resourceCulture);
            }
        }
        
        internal static string Packet_Serialize_WriterNullException {
            get {
                return ResourceManager.GetString("Packet_Serialize_WriterNullException", resourceCulture);
            }
        }
        
        internal static string PacketHeader_Serialize_WriterNullException {
            get {
                return ResourceManager.GetString("PacketHeader_Serialize_WriterNullException", resourceCulture);
            }
        }
        
        internal static string PacketHeader_Deserialize_NullReaderException {
            get {
                return ResourceManager.GetString("PacketHeader_Deserialize_NullReaderException", resourceCulture);
            }
        }
        
        internal static string StandardCommandHandler_AddUser_PasswordPrompt {
            get {
                return ResourceManager.GetString("StandardCommandHandler_AddUser_PasswordPrompt", resourceCulture);
            }
        }
        
        internal static string Server_StopAsync_Log {
            get {
                return ResourceManager.GetString("Server_StopAsync_Log", resourceCulture);
            }
        }
        
        internal static string ServerStatusCommandHandler_GetPassword_Backspace {
            get {
                return ResourceManager.GetString("ServerStatusCommandHandler_GetPassword_Backspace", resourceCulture);
            }
        }
        
        internal static string ServerStatusCommandHandler_GetPassword_Star {
            get {
                return ResourceManager.GetString("ServerStatusCommandHandler_GetPassword_Star", resourceCulture);
            }
        }
        
        internal static string Server_ConfigureAsync_ConfigFileNullException {
            get {
                return ResourceManager.GetString("Server_ConfigureAsync_ConfigFileNullException", resourceCulture);
            }
        }
    }
}
