//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uchu.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Uchu.Core.Resources.ResourceStrings", typeof(ResourceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received null bit reader in read.
        /// </summary>
        internal static string BitReader_Read_NullReaderException {
            get {
                return ResourceManager.GetString("BitReader_Read_NullReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received null serializable in read.
        /// </summary>
        internal static string BitReader_Read_NullSerializableException {
            get {
                return ResourceManager.GetString("BitReader_Read_NullSerializableException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received null bitreader in read bytes.
        /// </summary>
        internal static string BitReader_Readbytes_NullReaderException {
            get {
                return ResourceManager.GetString("BitReader_Readbytes_NullReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received null bit reader in read string.
        /// </summary>
        internal static string BitReader_ReadString_NullReaderException {
            get {
                return ResourceManager.GetString("BitReader_ReadString_NullReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received null writer in write.
        /// </summary>
        internal static string BitWriter_Write_NullWriterException {
            get {
                return ResourceManager.GetString("BitWriter_Write_NullWriterException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received null writer in write string.
        /// </summary>
        internal static string BitWriter_WriteString_NullWriterException {
            get {
                return ResourceManager.GetString("BitWriter_WriteString_NullWriterException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received null packet in validate client.
        /// </summary>
        internal static string ClientHandler_ValidateClient_PacketNullException {
            get {
                return ResourceManager.GetString("ClientHandler_ValidateClient_PacketNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received null endpoint in delete session.
        /// </summary>
        internal static string DatabaseCache_DeleteSession_NullEndpointException {
            get {
                return ResourceManager.GetString("DatabaseCache_DeleteSession_NullEndpointException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received null endpoint in get session.
        /// </summary>
        internal static string DatabaseCache_GetSessionAsync_NullEndpointException {
            get {
                return ResourceManager.GetString("DatabaseCache_GetSessionAsync_NullEndpointException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received null endpoint in register key.
        /// </summary>
        internal static string DatabaseCache_RegisterKey_NullEndpointException {
            get {
                return ResourceManager.GetString("DatabaseCache_RegisterKey_NullEndpointException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received null endpoint in set character.
        /// </summary>
        internal static string DatabaseCache_SetCharacter_NullEndpointException {
            get {
                return ResourceManager.GetString("DatabaseCache_SetCharacter_NullEndpointException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received null endpoint in set zone..
        /// </summary>
        internal static string DatabaseCache_SetZone_NullEndpointException {
            get {
                return ResourceManager.GetString("DatabaseCache_SetZone_NullEndpointException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received null reader in deserialize.
        /// </summary>
        internal static string DisconnectNotifyPacket_Deserialize_ReaderNullException {
            get {
                return ResourceManager.GetString("DisconnectNotifyPacket_Deserialize_ReaderNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received null writer in serialize packet.
        /// </summary>
        internal static string DisconnectNotifyPacket_Serialize_PacketWriterNullException {
            get {
                return ResourceManager.GetString("DisconnectNotifyPacket_Serialize_PacketWriterNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received null packet in handshake.
        /// </summary>
        internal static string GeneralHandler_Handshake_PacketNullException {
            get {
                return ResourceManager.GetString("GeneralHandler_Handshake_PacketNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received null reader in deserialize.
        /// </summary>
        internal static string HandshakePacket_Deserialize_ReaderNullException {
            get {
                return ResourceManager.GetString("HandshakePacket_Deserialize_ReaderNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received null writer in serialize packet.
        /// </summary>
        internal static string HandshakePacket_Serialize_WriterNullException {
            get {
                return ResourceManager.GetString("HandshakePacket_Serialize_WriterNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received null path in get stream.
        /// </summary>
        internal static string LocalResources_GetStream_PathNullException {
            get {
                return ResourceManager.GetString("LocalResources_GetStream_PathNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received null writer in serialize.
        /// </summary>
        internal static string Packet_Serialize_WriterNullException {
            get {
                return ResourceManager.GetString("Packet_Serialize_WriterNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received null reader in deserialize.
        /// </summary>
        internal static string PacketHeader_Deserialize_NullReaderException {
            get {
                return ResourceManager.GetString("PacketHeader_Deserialize_NullReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received null writer in serialize.
        /// </summary>
        internal static string PacketHeader_Serialize_WriterNullException {
            get {
                return ResourceManager.GetString("PacketHeader_Serialize_WriterNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received null connection in send.
        /// </summary>
        internal static string RakConnectionExtensions_Send_ConnectionNullException {
            get {
                return ResourceManager.GetString("RakConnectionExtensions_Send_ConnectionNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received null stream in send.
        /// </summary>
        internal static string RakConnectionExtensions_Send_StreamNullException {
            get {
                return ResourceManager.GetString("RakConnectionExtensions_Send_StreamNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create redis session cache from null config.
        /// </summary>
        internal static string RedisSessionCache_ConfigNullException {
            get {
                return ResourceManager.GetString("RedisSessionCache_ConfigNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received null endpoint in delete session.
        /// </summary>
        internal static string RedisSessionCache_DeleteSession_EndpointNullException {
            get {
                return ResourceManager.GetString("RedisSessionCache_DeleteSession_EndpointNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received null endpoint in get session..
        /// </summary>
        internal static string RedisSessioncache_GetSessionAsync_EndpointNullException {
            get {
                return ResourceManager.GetString("RedisSessioncache_GetSessionAsync_EndpointNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received null endpoint in register key..
        /// </summary>
        internal static string RedisSessionCache_RegisterKey_EndpointNullException {
            get {
                return ResourceManager.GetString("RedisSessionCache_RegisterKey_EndpointNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received null endpoint in setcharacter.
        /// </summary>
        internal static string RedisSessionCache_SetCharacter_EndpointNullException {
            get {
                return ResourceManager.GetString("RedisSessionCache_SetCharacter_EndpointNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received null endpoint in set zone..
        /// </summary>
        internal static string RedisSessionCache_SetZone_EndpointNullException {
            get {
                return ResourceManager.GetString("RedisSessionCache_SetZone_EndpointNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received null config file in configure.
        /// </summary>
        internal static string Server_ConfigureAsync_ConfigFileNullException {
            get {
                return ResourceManager.GetString("Server_ConfigureAsync_ConfigFileNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutting down ....
        /// </summary>
        internal static string Server_StopAsync_Log {
            get {
                return ResourceManager.GetString("Server_StopAsync_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string ServerStatusCommandHandler_GetPassword_Backspace {
            get {
                return ResourceManager.GetString("ServerStatusCommandHandler_GetPassword_Backspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string ServerStatusCommandHandler_GetPassword_Star {
            get {
                return ResourceManager.GetString("ServerStatusCommandHandler_GetPassword_Star", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received null arguments in add user.
        /// </summary>
        internal static string StandardCommandHandler_AddUser_ArgumentsNullException {
            get {
                return ResourceManager.GetString("StandardCommandHandler_AddUser_ArgumentsNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password: .
        /// </summary>
        internal static string StandardCommandHandler_AddUser_PasswordPrompt {
            get {
                return ResourceManager.GetString("StandardCommandHandler_AddUser_PasswordPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received null arguments in approve usernames.
        /// </summary>
        internal static string StandardCommandHandler_ApproveUsername_ArgumentsNullException {
            get {
                return ResourceManager.GetString("StandardCommandHandler_ApproveUsername_ArgumentsNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received null arguments in ban user.
        /// </summary>
        internal static string StandardCommandHandler_BanUser_ArgumentsNullException {
            get {
                return ResourceManager.GetString("StandardCommandHandler_BanUser_ArgumentsNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received null arguments in pardon user.
        /// </summary>
        internal static string StandardCommandHandler_PardonUser_ArgumentsNullException {
            get {
                return ResourceManager.GetString("StandardCommandHandler_PardonUser_ArgumentsNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received null arguments in reject user names.
        /// </summary>
        internal static string StandardCommandHandler_RejectUserNames_ArgumentsNullException {
            get {
                return ResourceManager.GetString("StandardCommandHandler_RejectUserNames_ArgumentsNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received null arguments in remove user.
        /// </summary>
        internal static string StandardCommandHandler_RemoveUser_ArgumentsNullException {
            get {
                return ResourceManager.GetString("StandardCommandHandler_RemoveUser_ArgumentsNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write the username again to confirm deletion: .
        /// </summary>
        internal static string StandardCommandHandler_RemoveUser_ConfirmationMessage {
            get {
                return ResourceManager.GetString("StandardCommandHandler_RemoveUser_ConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received null arguments in set game master level.
        /// </summary>
        internal static string StandardCommandHandler_SetGameMasterLevel_ArgumentsNullException {
            get {
                return ResourceManager.GetString("StandardCommandHandler_SetGameMasterLevel_ArgumentsNullException", resourceCulture);
            }
        }
    }
}
