namespace Uchu.Core
{
    public enum ZoneId : ushort
    {
        VentureExplorerCinematic,
        VentureExplorer = 1000,
        ReturnToVentureExplorer,
        AvantGardens = 1100,
        AvantGardensSurvival,
        SpiderQueenBattle,
        BlockYard = 1150,
        AvantGrove,
        NimbusStation = 1200,
        PetCove,
        VertigoLoopRacetrack = 1203,
        BattleOfNimbusStation,
        NimbusRock = 1250,
        NimbusIsle,
        FrostBurgh = 1260,
        GnarledForest = 1300,
        CanyonCove = 1302,
        KeelhaulCanyon,
        ChanteyShantey = 1350,
        ForbiddenValley = 1400,
        ForbiddenValleyDragon = 1402,
        DragonmawChasm,
        RavenBluff = 1450,
        Starbase3001 = 1600,
        DeepFreeze,
        RobotCity,
        MoonBase,
        Portabello = 1604,
        LegoClub = 1700,
        CruxPrime = 1800,
        NexusTower = 1900,
        Ninjago = 2000,
        FrakjawBattle,
        NimbusStationWinterRacetrack = 1261,
        Test = 58001
    }
}